name: Deploy to Aruba

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP
        run: sudo apt-get install -y lftp

      - name: Deploy
        run: |
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.USER_NAME }},${{ secrets.PRO }} ${{ secrets.SERVER }};"
